### ISSUE TITLE
[WEB] web Front 개발

### ISSUE THREAD

**Issue by Knowsoeun** [posco3-2/web#1]
## 💡 Issue
웹 프론트 개발

## 📝 todo
- [ ] 정렬 기능 추가
- [ ] 다크모드 전체 적용 (feat.Storage)
- [ ] 사용자 관리 페이지 개발
- [ ] 단말기 관리 페이지 개발
- [ ] 애플리케이션 관리 페이지 개발
- [ ] 회사 관리 페이지 개발
- [ ] header, 레이아웃 전체 정리
- [ ] 폴더, 파일 깔끔하게 전체 정리
